### PR TITLE
MSVC Port

### PR DESCRIPTION
**Pull request by jschueller**
- Avoid usage of VLAs which are unsupported, using std::vector instead
- Fix usage of INTEL flags in cmake
- complex numbers support is not great in msvc, modified examples macros
- fixed some warnings

### CODE REVIEW

**Comment by jeromerobert** [comment]
Perfect. thank you !

**Comment by jschueller** [comment]
is there a new version planned ?

**Comment by jeromerobert** [comment]
As you need. I just tagged 1.9.0.

**Comment by jschueller** [comment]
great!

**Pull request merged**
